const githubResponse = """ 
{
  "total_count": 15031,
  "incomplete_results": false,
  "items": [
    {
      "login": "matheus",
      "id": 3068278,
      "node_id": "MDQ6VXNlcjMwNjgyNzg=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/3068278?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/matheus",
      "html_url": "https://github.com/matheus",
      "followers_url": "https://api.github.com/users/matheus/followers",
      "following_url": "https://api.github.com/users/matheus/following{/other_user}",
      "gists_url": "https://api.github.com/users/matheus/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/matheus/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/matheus/subscriptions",
      "organizations_url": "https://api.github.com/users/matheus/orgs",
      "repos_url": "https://api.github.com/users/matheus/repos",
      "events_url": "https://api.github.com/users/matheus/events{/privacy}",
      "received_events_url": "https://api.github.com/users/matheus/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "embs",
      "id": 1200033,
      "node_id": "MDQ6VXNlcjEyMDAwMzM=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/1200033?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/embs",
      "html_url": "https://github.com/embs",
      "followers_url": "https://api.github.com/users/embs/followers",
      "following_url": "https://api.github.com/users/embs/following{/other_user}",
      "gists_url": "https://api.github.com/users/embs/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/embs/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/embs/subscriptions",
      "organizations_url": "https://api.github.com/users/embs/orgs",
      "repos_url": "https://api.github.com/users/embs/repos",
      "events_url": "https://api.github.com/users/embs/events{/privacy}",
      "received_events_url": "https://api.github.com/users/embs/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "matheuss",
      "id": 4721750,
      "node_id": "MDQ6VXNlcjQ3MjE3NTA=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/4721750?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/matheuss",
      "html_url": "https://github.com/matheuss",
      "followers_url": "https://api.github.com/users/matheuss/followers",
      "following_url": "https://api.github.com/users/matheuss/following{/other_user}",
      "gists_url": "https://api.github.com/users/matheuss/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/matheuss/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/matheuss/subscriptions",
      "organizations_url": "https://api.github.com/users/matheuss/orgs",
      "repos_url": "https://api.github.com/users/matheuss/repos",
      "events_url": "https://api.github.com/users/matheuss/events{/privacy}",
      "received_events_url": "https://api.github.com/users/matheuss/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "matheusml",
      "id": 444202,
      "node_id": "MDQ6VXNlcjQ0NDIwMg==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/444202?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/matheusml",
      "html_url": "https://github.com/matheusml",
      "followers_url": "https://api.github.com/users/matheusml/followers",
      "following_url": "https://api.github.com/users/matheusml/following{/other_user}",
      "gists_url": "https://api.github.com/users/matheusml/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/matheusml/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/matheusml/subscriptions",
      "organizations_url": "https://api.github.com/users/matheusml/orgs",
      "repos_url": "https://api.github.com/users/matheusml/repos",
      "events_url": "https://api.github.com/users/matheusml/events{/privacy}",
      "received_events_url": "https://api.github.com/users/matheusml/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "onhernandes",
      "id": 12698656,
      "node_id": "MDQ6VXNlcjEyNjk4NjU2",
      "avatar_url": "https://avatars2.githubusercontent.com/u/12698656?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/onhernandes",
      "html_url": "https://github.com/onhernandes",
      "followers_url": "https://api.github.com/users/onhernandes/followers",
      "following_url": "https://api.github.com/users/onhernandes/following{/other_user}",
      "gists_url": "https://api.github.com/users/onhernandes/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/onhernandes/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/onhernandes/subscriptions",
      "organizations_url": "https://api.github.com/users/onhernandes/orgs",
      "repos_url": "https://api.github.com/users/onhernandes/repos",
      "events_url": "https://api.github.com/users/onhernandes/events{/privacy}",
      "received_events_url": "https://api.github.com/users/onhernandes/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "cardoso",
      "id": 5606812,
      "node_id": "MDQ6VXNlcjU2MDY4MTI=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/5606812?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cardoso",
      "html_url": "https://github.com/cardoso",
      "followers_url": "https://api.github.com/users/cardoso/followers",
      "following_url": "https://api.github.com/users/cardoso/following{/other_user}",
      "gists_url": "https://api.github.com/users/cardoso/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cardoso/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cardoso/subscriptions",
      "organizations_url": "https://api.github.com/users/cardoso/orgs",
      "repos_url": "https://api.github.com/users/cardoso/repos",
      "events_url": "https://api.github.com/users/cardoso/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cardoso/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "matheusgr",
      "id": 882438,
      "node_id": "MDQ6VXNlcjg4MjQzOA==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/882438?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/matheusgr",
      "html_url": "https://github.com/matheusgr",
      "followers_url": "https://api.github.com/users/matheusgr/followers",
      "following_url": "https://api.github.com/users/matheusgr/following{/other_user}",
      "gists_url": "https://api.github.com/users/matheusgr/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/matheusgr/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/matheusgr/subscriptions",
      "organizations_url": "https://api.github.com/users/matheusgr/orgs",
      "repos_url": "https://api.github.com/users/matheusgr/repos",
      "events_url": "https://api.github.com/users/matheusgr/events{/privacy}",
      "received_events_url": "https://api.github.com/users/matheusgr/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "matheusbattisti",
      "id": 11837941,
      "node_id": "MDQ6VXNlcjExODM3OTQx",
      "avatar_url": "https://avatars2.githubusercontent.com/u/11837941?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/matheusbattisti",
      "html_url": "https://github.com/matheusbattisti",
      "followers_url": "https://api.github.com/users/matheusbattisti/followers",
      "following_url": "https://api.github.com/users/matheusbattisti/following{/other_user}",
      "gists_url": "https://api.github.com/users/matheusbattisti/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/matheusbattisti/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/matheusbattisti/subscriptions",
      "organizations_url": "https://api.github.com/users/matheusbattisti/orgs",
      "repos_url": "https://api.github.com/users/matheusbattisti/repos",
      "events_url": "https://api.github.com/users/matheusbattisti/events{/privacy}",
      "received_events_url": "https://api.github.com/users/matheusbattisti/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "matheusfrancisco",
      "id": 6428732,
      "node_id": "MDQ6VXNlcjY0Mjg3MzI=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/6428732?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/matheusfrancisco",
      "html_url": "https://github.com/matheusfrancisco",
      "followers_url": "https://api.github.com/users/matheusfrancisco/followers",
      "following_url": "https://api.github.com/users/matheusfrancisco/following{/other_user}",
      "gists_url": "https://api.github.com/users/matheusfrancisco/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/matheusfrancisco/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/matheusfrancisco/subscriptions",
      "organizations_url": "https://api.github.com/users/matheusfrancisco/orgs",
      "repos_url": "https://api.github.com/users/matheusfrancisco/repos",
      "events_url": "https://api.github.com/users/matheusfrancisco/events{/privacy}",
      "received_events_url": "https://api.github.com/users/matheusfrancisco/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "matheusfacure",
      "id": 18542597,
      "node_id": "MDQ6VXNlcjE4NTQyNTk3",
      "avatar_url": "https://avatars0.githubusercontent.com/u/18542597?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/matheusfacure",
      "html_url": "https://github.com/matheusfacure",
      "followers_url": "https://api.github.com/users/matheusfacure/followers",
      "following_url": "https://api.github.com/users/matheusfacure/following{/other_user}",
      "gists_url": "https://api.github.com/users/matheusfacure/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/matheusfacure/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/matheusfacure/subscriptions",
      "organizations_url": "https://api.github.com/users/matheusfacure/orgs",
      "repos_url": "https://api.github.com/users/matheusfacure/repos",
      "events_url": "https://api.github.com/users/matheusfacure/events{/privacy}",
      "received_events_url": "https://api.github.com/users/matheusfacure/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "matheus-vieira",
      "id": 2846463,
      "node_id": "MDQ6VXNlcjI4NDY0NjM=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/2846463?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/matheus-vieira",
      "html_url": "https://github.com/matheus-vieira",
      "followers_url": "https://api.github.com/users/matheus-vieira/followers",
      "following_url": "https://api.github.com/users/matheus-vieira/following{/other_user}",
      "gists_url": "https://api.github.com/users/matheus-vieira/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/matheus-vieira/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/matheus-vieira/subscriptions",
      "organizations_url": "https://api.github.com/users/matheus-vieira/orgs",
      "repos_url": "https://api.github.com/users/matheus-vieira/repos",
      "events_url": "https://api.github.com/users/matheus-vieira/events{/privacy}",
      "received_events_url": "https://api.github.com/users/matheus-vieira/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "matheuslc",
      "id": 4161171,
      "node_id": "MDQ6VXNlcjQxNjExNzE=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/4161171?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/matheuslc",
      "html_url": "https://github.com/matheuslc",
      "followers_url": "https://api.github.com/users/matheuslc/followers",
      "following_url": "https://api.github.com/users/matheuslc/following{/other_user}",
      "gists_url": "https://api.github.com/users/matheuslc/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/matheuslc/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/matheuslc/subscriptions",
      "organizations_url": "https://api.github.com/users/matheuslc/orgs",
      "repos_url": "https://api.github.com/users/matheuslc/repos",
      "events_url": "https://api.github.com/users/matheuslc/events{/privacy}",
      "received_events_url": "https://api.github.com/users/matheuslc/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "MatheusGrijo",
      "id": 7804469,
      "node_id": "MDQ6VXNlcjc4MDQ0Njk=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/7804469?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MatheusGrijo",
      "html_url": "https://github.com/MatheusGrijo",
      "followers_url": "https://api.github.com/users/MatheusGrijo/followers",
      "following_url": "https://api.github.com/users/MatheusGrijo/following{/other_user}",
      "gists_url": "https://api.github.com/users/MatheusGrijo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MatheusGrijo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MatheusGrijo/subscriptions",
      "organizations_url": "https://api.github.com/users/MatheusGrijo/orgs",
      "repos_url": "https://api.github.com/users/MatheusGrijo/repos",
      "events_url": "https://api.github.com/users/MatheusGrijo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MatheusGrijo/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "matheusd",
      "id": 1752493,
      "node_id": "MDQ6VXNlcjE3NTI0OTM=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/1752493?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/matheusd",
      "html_url": "https://github.com/matheusd",
      "followers_url": "https://api.github.com/users/matheusd/followers",
      "following_url": "https://api.github.com/users/matheusd/following{/other_user}",
      "gists_url": "https://api.github.com/users/matheusd/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/matheusd/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/matheusd/subscriptions",
      "organizations_url": "https://api.github.com/users/matheusd/orgs",
      "repos_url": "https://api.github.com/users/matheusd/repos",
      "events_url": "https://api.github.com/users/matheusd/events{/privacy}",
      "received_events_url": "https://api.github.com/users/matheusd/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "matheusazzi",
      "id": 1292945,
      "node_id": "MDQ6VXNlcjEyOTI5NDU=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/1292945?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/matheusazzi",
      "html_url": "https://github.com/matheusazzi",
      "followers_url": "https://api.github.com/users/matheusazzi/followers",
      "following_url": "https://api.github.com/users/matheusazzi/following{/other_user}",
      "gists_url": "https://api.github.com/users/matheusazzi/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/matheusazzi/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/matheusazzi/subscriptions",
      "organizations_url": "https://api.github.com/users/matheusazzi/orgs",
      "repos_url": "https://api.github.com/users/matheusazzi/repos",
      "events_url": "https://api.github.com/users/matheusazzi/events{/privacy}",
      "received_events_url": "https://api.github.com/users/matheusazzi/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "MatheusRV",
      "id": 23284276,
      "node_id": "MDQ6VXNlcjIzMjg0Mjc2",
      "avatar_url": "https://avatars0.githubusercontent.com/u/23284276?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MatheusRV",
      "html_url": "https://github.com/MatheusRV",
      "followers_url": "https://api.github.com/users/MatheusRV/followers",
      "following_url": "https://api.github.com/users/MatheusRV/following{/other_user}",
      "gists_url": "https://api.github.com/users/MatheusRV/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MatheusRV/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MatheusRV/subscriptions",
      "organizations_url": "https://api.github.com/users/MatheusRV/orgs",
      "repos_url": "https://api.github.com/users/MatheusRV/repos",
      "events_url": "https://api.github.com/users/MatheusRV/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MatheusRV/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "matheusmurta",
      "id": 15116383,
      "node_id": "MDQ6VXNlcjE1MTE2Mzgz",
      "avatar_url": "https://avatars3.githubusercontent.com/u/15116383?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/matheusmurta",
      "html_url": "https://github.com/matheusmurta",
      "followers_url": "https://api.github.com/users/matheusmurta/followers",
      "following_url": "https://api.github.com/users/matheusmurta/following{/other_user}",
      "gists_url": "https://api.github.com/users/matheusmurta/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/matheusmurta/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/matheusmurta/subscriptions",
      "organizations_url": "https://api.github.com/users/matheusmurta/orgs",
      "repos_url": "https://api.github.com/users/matheusmurta/repos",
      "events_url": "https://api.github.com/users/matheusmurta/events{/privacy}",
      "received_events_url": "https://api.github.com/users/matheusmurta/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Matheus28",
      "id": 614967,
      "node_id": "MDQ6VXNlcjYxNDk2Nw==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/614967?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Matheus28",
      "html_url": "https://github.com/Matheus28",
      "followers_url": "https://api.github.com/users/Matheus28/followers",
      "following_url": "https://api.github.com/users/Matheus28/following{/other_user}",
      "gists_url": "https://api.github.com/users/Matheus28/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Matheus28/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Matheus28/subscriptions",
      "organizations_url": "https://api.github.com/users/Matheus28/orgs",
      "repos_url": "https://api.github.com/users/Matheus28/repos",
      "events_url": "https://api.github.com/users/Matheus28/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Matheus28/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "condini-mastheus",
      "id": 12428539,
      "node_id": "MDQ6VXNlcjEyNDI4NTM5",
      "avatar_url": "https://avatars3.githubusercontent.com/u/12428539?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/condini-mastheus",
      "html_url": "https://github.com/condini-mastheus",
      "followers_url": "https://api.github.com/users/condini-mastheus/followers",
      "following_url": "https://api.github.com/users/condini-mastheus/following{/other_user}",
      "gists_url": "https://api.github.com/users/condini-mastheus/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/condini-mastheus/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/condini-mastheus/subscriptions",
      "organizations_url": "https://api.github.com/users/condini-mastheus/orgs",
      "repos_url": "https://api.github.com/users/condini-mastheus/repos",
      "events_url": "https://api.github.com/users/condini-mastheus/events{/privacy}",
      "received_events_url": "https://api.github.com/users/condini-mastheus/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "matheusportela",
      "id": 2743105,
      "node_id": "MDQ6VXNlcjI3NDMxMDU=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/2743105?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/matheusportela",
      "html_url": "https://github.com/matheusportela",
      "followers_url": "https://api.github.com/users/matheusportela/followers",
      "following_url": "https://api.github.com/users/matheusportela/following{/other_user}",
      "gists_url": "https://api.github.com/users/matheusportela/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/matheusportela/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/matheusportela/subscriptions",
      "organizations_url": "https://api.github.com/users/matheusportela/orgs",
      "repos_url": "https://api.github.com/users/matheusportela/repos",
      "events_url": "https://api.github.com/users/matheusportela/events{/privacy}",
      "received_events_url": "https://api.github.com/users/matheusportela/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "MatheusFreitag",
      "id": 2220005,
      "node_id": "MDQ6VXNlcjIyMjAwMDU=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/2220005?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MatheusFreitag",
      "html_url": "https://github.com/MatheusFreitag",
      "followers_url": "https://api.github.com/users/MatheusFreitag/followers",
      "following_url": "https://api.github.com/users/MatheusFreitag/following{/other_user}",
      "gists_url": "https://api.github.com/users/MatheusFreitag/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MatheusFreitag/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MatheusFreitag/subscriptions",
      "organizations_url": "https://api.github.com/users/MatheusFreitag/orgs",
      "repos_url": "https://api.github.com/users/MatheusFreitag/repos",
      "events_url": "https://api.github.com/users/MatheusFreitag/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MatheusFreitag/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "matheuscorreia",
      "id": 18041760,
      "node_id": "MDQ6VXNlcjE4MDQxNzYw",
      "avatar_url": "https://avatars3.githubusercontent.com/u/18041760?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/matheuscorreia",
      "html_url": "https://github.com/matheuscorreia",
      "followers_url": "https://api.github.com/users/matheuscorreia/followers",
      "following_url": "https://api.github.com/users/matheuscorreia/following{/other_user}",
      "gists_url": "https://api.github.com/users/matheuscorreia/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/matheuscorreia/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/matheuscorreia/subscriptions",
      "organizations_url": "https://api.github.com/users/matheuscorreia/orgs",
      "repos_url": "https://api.github.com/users/matheuscorreia/repos",
      "events_url": "https://api.github.com/users/matheuscorreia/events{/privacy}",
      "received_events_url": "https://api.github.com/users/matheuscorreia/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "matheuspoleza",
      "id": 8049914,
      "node_id": "MDQ6VXNlcjgwNDk5MTQ=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/8049914?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/matheuspoleza",
      "html_url": "https://github.com/matheuspoleza",
      "followers_url": "https://api.github.com/users/matheuspoleza/followers",
      "following_url": "https://api.github.com/users/matheuspoleza/following{/other_user}",
      "gists_url": "https://api.github.com/users/matheuspoleza/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/matheuspoleza/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/matheuspoleza/subscriptions",
      "organizations_url": "https://api.github.com/users/matheuspoleza/orgs",
      "repos_url": "https://api.github.com/users/matheuspoleza/repos",
      "events_url": "https://api.github.com/users/matheuspoleza/events{/privacy}",
      "received_events_url": "https://api.github.com/users/matheuspoleza/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "matheusrocha89",
      "id": 3718366,
      "node_id": "MDQ6VXNlcjM3MTgzNjY=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/3718366?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/matheusrocha89",
      "html_url": "https://github.com/matheusrocha89",
      "followers_url": "https://api.github.com/users/matheusrocha89/followers",
      "following_url": "https://api.github.com/users/matheusrocha89/following{/other_user}",
      "gists_url": "https://api.github.com/users/matheusrocha89/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/matheusrocha89/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/matheusrocha89/subscriptions",
      "organizations_url": "https://api.github.com/users/matheusrocha89/orgs",
      "repos_url": "https://api.github.com/users/matheusrocha89/repos",
      "events_url": "https://api.github.com/users/matheusrocha89/events{/privacy}",
      "received_events_url": "https://api.github.com/users/matheusrocha89/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "MatheusAvellar",
      "id": 1719996,
      "node_id": "MDQ6VXNlcjE3MTk5OTY=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/1719996?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MatheusAvellar",
      "html_url": "https://github.com/MatheusAvellar",
      "followers_url": "https://api.github.com/users/MatheusAvellar/followers",
      "following_url": "https://api.github.com/users/MatheusAvellar/following{/other_user}",
      "gists_url": "https://api.github.com/users/MatheusAvellar/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MatheusAvellar/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MatheusAvellar/subscriptions",
      "organizations_url": "https://api.github.com/users/MatheusAvellar/orgs",
      "repos_url": "https://api.github.com/users/MatheusAvellar/repos",
      "events_url": "https://api.github.com/users/MatheusAvellar/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MatheusAvellar/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "mthbernardes",
      "id": 12648924,
      "node_id": "MDQ6VXNlcjEyNjQ4OTI0",
      "avatar_url": "https://avatars0.githubusercontent.com/u/12648924?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mthbernardes",
      "html_url": "https://github.com/mthbernardes",
      "followers_url": "https://api.github.com/users/mthbernardes/followers",
      "following_url": "https://api.github.com/users/mthbernardes/following{/other_user}",
      "gists_url": "https://api.github.com/users/mthbernardes/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mthbernardes/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mthbernardes/subscriptions",
      "organizations_url": "https://api.github.com/users/mthbernardes/orgs",
      "repos_url": "https://api.github.com/users/mthbernardes/repos",
      "events_url": "https://api.github.com/users/mthbernardes/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mthbernardes/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "MatheusPires99",
      "id": 49207932,
      "node_id": "MDQ6VXNlcjQ5MjA3OTMy",
      "avatar_url": "https://avatars3.githubusercontent.com/u/49207932?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MatheusPires99",
      "html_url": "https://github.com/MatheusPires99",
      "followers_url": "https://api.github.com/users/MatheusPires99/followers",
      "following_url": "https://api.github.com/users/MatheusPires99/following{/other_user}",
      "gists_url": "https://api.github.com/users/MatheusPires99/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MatheusPires99/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MatheusPires99/subscriptions",
      "organizations_url": "https://api.github.com/users/MatheusPires99/orgs",
      "repos_url": "https://api.github.com/users/MatheusPires99/repos",
      "events_url": "https://api.github.com/users/MatheusPires99/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MatheusPires99/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "MatheusHonorato",
      "id": 19641180,
      "node_id": "MDQ6VXNlcjE5NjQxMTgw",
      "avatar_url": "https://avatars2.githubusercontent.com/u/19641180?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MatheusHonorato",
      "html_url": "https://github.com/MatheusHonorato",
      "followers_url": "https://api.github.com/users/MatheusHonorato/followers",
      "following_url": "https://api.github.com/users/MatheusHonorato/following{/other_user}",
      "gists_url": "https://api.github.com/users/MatheusHonorato/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MatheusHonorato/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MatheusHonorato/subscriptions",
      "organizations_url": "https://api.github.com/users/MatheusHonorato/orgs",
      "repos_url": "https://api.github.com/users/MatheusHonorato/repos",
      "events_url": "https://api.github.com/users/MatheusHonorato/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MatheusHonorato/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "matheusps",
      "id": 6964311,
      "node_id": "MDQ6VXNlcjY5NjQzMTE=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/6964311?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/matheusps",
      "html_url": "https://github.com/matheusps",
      "followers_url": "https://api.github.com/users/matheusps/followers",
      "following_url": "https://api.github.com/users/matheusps/following{/other_user}",
      "gists_url": "https://api.github.com/users/matheusps/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/matheusps/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/matheusps/subscriptions",
      "organizations_url": "https://api.github.com/users/matheusps/orgs",
      "repos_url": "https://api.github.com/users/matheusps/repos",
      "events_url": "https://api.github.com/users/matheusps/events{/privacy}",
      "received_events_url": "https://api.github.com/users/matheusps/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ythecombinator",
      "id": 2644563,
      "node_id": "MDQ6VXNlcjI2NDQ1NjM=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/2644563?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ythecombinator",
      "html_url": "https://github.com/ythecombinator",
      "followers_url": "https://api.github.com/users/ythecombinator/followers",
      "following_url": "https://api.github.com/users/ythecombinator/following{/other_user}",
      "gists_url": "https://api.github.com/users/ythecombinator/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ythecombinator/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ythecombinator/subscriptions",
      "organizations_url": "https://api.github.com/users/ythecombinator/orgs",
      "repos_url": "https://api.github.com/users/ythecombinator/repos",
      "events_url": "https://api.github.com/users/ythecombinator/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ythecombinator/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
  ]
}
""";
